Issue#10290_complete_iso_contact_roles_per_ressource_base_with_multiplicity
GeoNode/geonode pull request #10367
Opened 2022-11-30 10:38 UTC by mwallschlaeger

<Include a few sentences describing the overall goals for this Pull Request>
This is a work in progress PR to give an overview and first feedback from as the changes getting a little out of hand. 

What the current state is aware of:
- showing all contact roles via the rest API v2
- handling contact roles in metadata editor for dataset, I guess i would fully adopt this the same way for documents, maps and geoapps. I started working on this already (see changes).
- adopted resource base model to handle all contact roles and be able to set multiple authors for one role 

I know that further work in this topic at least requires changes to the following sections/files:

### Todos
#### catalog:
- [ ] geonode_metadata_full.html
- [ ] _resourcebase_info_panel.html
- [ ] people/_profile_about_item.html
#### layers
- [ ] dataset_metadata.html
#### maps
- [ ] panel.html
- [ ] map_metadata_advanced.html
#### documents
- [ ] panel.html
- [ ] map_metadata_advanced.html

#### geoapps
- [ ] geoapps-> views, panel and so on ...
For me there is the question on also changing the handling on geoapps, too. I guess i would go for it to make all child's of resource_base behave the same in this matter. 

#### harvesting
- [ ] geonodeharvester.py

There is even more files to change apart from the ones already changed an the ones listed above. Further tests have to be added to this PR.

I'm willing to further work on this issue the upcoming weeks, but I think it is good to get some advice from the PSC to see if the direction this is going fits the ideas of the committee members.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

2022-12-09 18:36 UTC, MalteIwanicki commented
[This PR](https://github.com/GeoNode/geonode-mapstore-client/pull/1360) also needs to be merged when we wanna use a list instead of a single contact for point of contact.

2022-12-14 23:05 UTC, MalteIwanicki commented
I took care of the contacts in the `geonode_metadata_full.html`. Once I can commit to your branch it's there

2023-01-13 09:02 UTC, gannebamm commented
@MalteIwanicki @mwallschlaeger please take a peak at https://github.com/GeoNode/geonode/issues/10521
I think the mentioned changes could improve this draft PR

2023-03-17 18:24 UTC, gannebamm commented
@mwallschlaeger Can we get a status report on this draft? What is missing. do you need help?

2023-03-20 11:08 UTC, mwallschlaeger commented
Hi,

yes actually I'm waiting for @ahmdthr for a final commit to this PR, so we could leave the draft state. But i haven't heard from him in a while

2023-04-15 11:33 UTC, gannebamm commented
@mwallschlaeger is this ready for review?

2023-04-17 06:35 UTC, mwallschlaeger commented
@gannebamm yes it would be very good if smb. would check this PR and gives us feedback about further required changes

2023-04-17 08:43 UTC, giohappy commented
@mwallschlaeger we will make some tests on our side. Overall it looks quite good so far. There are few places where we might add small comments.

2023-04-17 09:04 UTC, giohappy reviewed
@mwallschlaeger after adding multiple Points of Contacts they're listed inside the metadata detail but the editing field (both inside the wizard and the advacned page) only shows the first one.

2023-04-17 11:12 UTC, mattiagiupponi submitted a review, later dismissed
Hi @mwallschlaeger 
Follows some first impression about the PR, since is huge it will take some time to review it properly

2023-04-17 11:12 UTC, mattiagiupponi commented on geonode/base/models.py
> +    def poc_csv(self):
I'll evaluate changing the name on `poc_as_csv` for all the new configurations added to make it more explicit

2023-04-17 11:12 UTC, mattiagiupponi commented on geonode/geoserver/helpers.py
> +                        profile = get_user_model().objects.get(username=instance.poc[0].username)
I agree, access directly to the list index could be error prone

2023-04-17 11:12 UTC, mattiagiupponi commented on geonode/locale/it/LC_MESSAGES/django.po
> +msgstr "mostrare più ruoli"
You can change this in `mostra più ruoli`

2023-04-17 11:12 UTC, mattiagiupponi commented on geonode/maps/templates/layouts/map_panels.html
> +            <div class="panel panel-default panel-collapse collapse" collapsed id='id-more-metadata-panel'>
To reduce the verbosity in the HTML cannot we have a simple loop based on an enum where we can define the names and use it to generate the HTML??

2023-04-17 11:12 UTC, mattiagiupponi commented on geonode/layers/views.py
> +        layer.set_contact_roles_from_metadata_edit(dataset_form)
I see that the method `set_contact_roles_from_metadata_edit` return a `failed=True` if something went wrong.
If for any reason is not possible to set the contact roles, isn't it better to make the save fail?
even something like:

```python
is_failed = layer.set_contact_roles_from_metadata_edit(dataset_form)
if is_failed:
    raise Exception("Error during the contact role assignment")
```

2023-04-25 07:27 UTC, ridoo commented
> [This PR](https://github.com/GeoNode/geonode-mapstore-client/pull/1360) also needs to be merged when we wanna use a list instead of a single contact for point of contact.

That PR is outdated (and even fails to start). However, GMSC has a refactored the DetailsViewer component now and POCs are configurable in the `localConfig.json` now. Looping over a list of POCs should be done [in the plugin context utility](https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/client/js/utils/PluginsContextUtils.js#L24) .

2023-04-28 09:22 UTC, ridoo commented
PR https://github.com/GeoNode/geonode-mapstore-client/pull/1421 supersedes PR https://github.com/GeoNode/geonode-mapstore-client/pull/1360 and a respects recent refactoring of  `DetailInfos`.

2023-05-24 13:11 UTC, giohappy commented
@ridoo can you please take a look at the conflicts?

2023-05-24 15:52 UTC, ridoo commented
@giohappy fixed it .. please have a look at my comment https://github.com/GeoNode/geonode-mapstore-client/pull/1421#issuecomment-1561350515

2023-08-10 12:33 UTC, mwallschlaeger commented
I will do some checks again on this PR related to the rest-api and than reopen it again for a review.

2023-08-23 09:56 UTC, mwallschlaeger commented
ok, fixed an issue related to the API, but now I think it's ready for a review again. I used https://github.com/GeoNodeUserGroup-DE/geonodectl to set contact roles via API using something like: `./geonodectl ds patch 1 --set '{"processor": [{ "pk": 1000, "username": "testuser" }, { "pk": 1001 }]}'`

2023-09-12 08:45 UTC, mwallschlaeger commented
i will check them

2023-10-06 14:25 UTC, mwallschlaeger commented
@giohappy :-) Could you give me another review on this PR so we can bring it to an end?^^

2023-10-17 13:55 UTC, giohappy commented
Hi @mwallschlaeger. Unfortunately, there are conflicts again since a few changes have been committed recently to the metadata editor templates. They should be easy to fix.

We took another look at the PR. We don't see anything that blocks its merge, although we would have some remarks, in particular on the choice of showing all the possible roles inside the editor, instead of giving the choice to add them dynamically (like with a plus button). 

Hopefully, the metadata editor will be rewritten, and this new functionality will have to be taken into account for the new version.

2023-10-18 08:49 UTC, giohappy commented
@mwallschlaeger please take a look at the failing test

2023-10-18 12:19 UTC, mwallschlaeger commented
@giohappy review pls

2023-10-19 15:53 UTC, giohappy commented
@mwallschlaeger I'm testing it right now. I can see the new widgets and I'm able to select multiple users, but they're not saved to the DB. both the metadata editor and the API keep showing a single user.

2023-10-20 07:11 UTC, mwallschlaeger commented
@giohappy i will check this again. but what I recognized when I applied those changes to an existing Geonode Instance is that there are migrations required for the already uploaded resources

2023-10-20 08:02 UTC, giohappy commented
>@giohappy i will check this again. but what I recognized when I applied those changes to an existing Geonode Instance is that there are migrations required for the already uploaded resources

which migrations @mwallschlaeger? I don'ìt see migrations in your PR

2023-10-20 09:31 UTC, mwallschlaeger commented
> > @giohappy i will check this again. but what I recognized when I applied those changes to an existing Geonode Instance is that there are migrations required for the already uploaded resources
> 
> which migrations @mwallschlaeger? I don'ìt see migrations in your PR

Hey the migrations are not included yet. but I tested this again they are not required. Regarding your issue. I cannot confirm that multiple users are not set correctly. Actually there is also a test for this case in `geonode.layers.tests.test_resource_form_is_valid_multiple_user_contact_role_as_queryset` and `geonode.layers.tests.test_patch_processor` and so on are tests setting multiple users for one contact role.

Can you please doublecheck that you have the right commit?

2023-10-20 09:45 UTC, giohappy commented
@mwallschlaeger ok, I will double check, BTW your latest merges seem to have broken the tests again.

2023-10-20 09:49 UTC, giohappy commented
@MalteIwanicki I confirm it works as expected now. I think this can be merged as soon as the tests are fixes.

2023-10-20 14:04 UTC, MalteIwanicki commented
@giohappy @ridoo  I'm totally out of the loop for this PR, not knowing what it was about. It has been over a year. Do you need any action from my side?

2023-10-20 14:14 UTC, ridoo commented
> @giohappy @ridoo I'm totally out of the loop for this PR, not knowing what it was about. It has been over a year. Do you need any action from my side?

@MalteIwanicki no problem at all :)

2023-10-20 14:59 UTC, giohappy requested changes

2023-10-20 14:59 UTC, giohappy commented on geonode/base/models.py
> -    image = models.CharField(max_length=512, help_text="A URL to an image", null=True, blank=True)
@mwallschlaeger why did you drop this field? It was introduced in https://github.com/GeoNode/geonode/commit/c437a0a69054217976fa519b245e82966543dbe5

2023-10-20 14:59 UTC, etj commented on geonode/base/models.py
> -    image = models.CharField(max_length=512, help_text="A URL to an image", null=True, blank=True)
This field has been removed

2023-10-23 12:37 UTC, giohappy approved these changes

2023-10-23 13:08 UTC, merged

2024-04-17 14:18 UTC, giohappy commented
@mwallschlaeger FYI we're investigating several problems that were reported with the management of contacts in metadata. It's broken in many ways. We will open an issue soon but I was curious to know if you did notice the problems it's giving, like:

 - contacts are not saved correctly or they're not saved at all
 - the layout for documents is broken

2024-04-17 15:47 UTC, mwallschlaeger commented
@giohappy hey i have noticed one issue I have fixed in our fork. i can at least play the one I have fixed back to core in the next days

2024-04-17 16:33 UTC, giohappy commented
@mwallschlaeger do you mean that editing of contacts works fine (except the issue you mentioned)?
If you try on the [stable demo](https://stable.demo.geonode.org/) you'll see that the changes to contacts are not saved.

2024-04-18 08:08 UTC, giohappy commented
@mwallschlaeger I've seen your PR but tests are failing. You're using `getlist` on a dict object.
I wonder how much your fork has diverged from this.

If it cannot be easily fixed we will be forced to revert the commit the commits. I have built a Docker image at the commit of your PR and it seems they weren't working even at that time. Something must be changed between my tests of your PR and its merge.

2024-04-18 08:43 UTC, gannebamm commented
@vineetasharma105 

Please check this in our dev instance.

2024-04-18 09:04 UTC, gannebamm commented
@giohappy If this is not easily fixable, than my +1 for reverting the changes for now.

2024-04-18 09:37 UTC, mwallschlaeger commented
@giohappy I guess i figured it out now. The test which are failing are providing the form data using the data argument, which passes and empty dict to the not filled contact roles, where `getlist` cannot be executed on. 

As in e.g.
https://github.com/GeoNode/geonode/blob/75edcdb50417f96d858b25b46a0998db6fe2ec14/geonode/layers/views.py#L532

they get filled via `initial`.

Another problem I came across investigating this, was that contact roles couldn't be removed also this was related to the change of the expected object type in widgets.py.

I'm gonna run the tests now locally and commit the changes to the PR, so you can check it, too.

2024-04-18 09:56 UTC, giohappy commented
@mwallschlaeger noticed that we see different behavior between stable demo (4.2.x) and master demo. 

The latter is even more worrying because changes are applied when a user is selected for a role, but the resulting saved user is different from the one that was selected.