Fix #11154 - Wrong login URL in notification
GeoNode/geonode pull request #11155
Opened 2023-06-09 21:56 UTC by fvicent

Quick fix for https://github.com/GeoNode/geonode/issues/11154

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: black geonode && flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

2023-06-12 09:23 UTC, gannebamm commented on geonode/people/models.py
> +                    'LOGIN_URL': settings.LOGIN_URL,
I think the Circle CI test does not like this to have `'` instead of `"` for the variable `LOGIN_URL` ? See failed test.

2023-06-12 09:25 UTC, gannebamm commented on geonode/people/models.py
> +                    'LOGIN_URL': settings.LOGIN_URL,
> ^@^@would reformat /usr/src/geonode/geonode/people/models.py
>Oh no! 💥 💔 💥
1 file would be reformatted, 479 files would be left unchanged.

2023-06-30 12:19 UTC, afabiani commented
Despite the change is small and useful, we can't merge this one until the formatting issues have been fixed.

2023-06-30 12:20 UTC, afabiani requested changes
Fix the formatting issues: Run `black geonode` and push again.

2023-07-03 08:35 UTC, merged