Issue 11853
GeoNode/geonode pull request #11893
Opened 2024-01-26 17:14 UTC by RegisSinjari

<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: black geonode && flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

2024-01-29 11:41 UTC, mattiagiupponi requested changes
Hi @RegisSinjari 
Please:
- set the PR in `ready for review` if is ready
- fix the PR title it should be like "[Fixes #ISSUENUMB] ISSUE title"

2024-01-29 11:41 UTC, mattiagiupponi commented on geonode/facets/tests.py
> +        group_profile_common = GroupProfile.objects.create(group_id=group_common, title="UserCommon", slug="UserCommon")
Lets' group the Group creation in a class function like the others `_create_resources`. Later you can just re-call them

2024-01-29 11:58 UTC, mattiagiupponi commented on geonode/facets/providers/group.py
> +        logger.warning(f" q.count()  {q.count()}")
No need to have this log at warning, please set it as debug in case

2024-01-29 11:58 UTC, mattiagiupponi commented on geonode/facets/providers/group.py
> +        logger.warning(" FINAL QUERY        ---> %s\n\n", q.query)
No need to have this log at warning, please set it as debug in case

2024-01-30 16:38 UTC, etj requested changes
Please note that facest filtering interact each other.
Pls improve / augment tests which perform queries on multiple facets (e.g. `test_count0`)

2024-02-01 13:15 UTC, etj commented on geonode/facets/tests.py
> +from django.contrib.auth.models import Group
pls move close to the other django,contrib imports

2024-02-02 15:21 UTC, mattiagiupponi approved these changes

2024-02-05 10:18 UTC, etj requested changes
Pls don't use explicit IDs as "magic numbers"

2024-02-05 10:18 UTC, etj commented on geonode/facets/tests.py
> +            (grname, {grflt: [4], "key": [4]}, {4: 7}),
Are we using explicit group IDs? Where do they come from?
Pls note that for all other objects we store the IDs generated by the DB in some sort of dict (`thesauri_k`) or use some slug (`R0`, `R1`,`R2` for regions, `C0`, `C1`, `C2` for categories)...

2024-02-05 12:45 UTC, etj approved these changes

2024-02-05 13:21 UTC, merged