Bump 4.2.x to dev
GeoNode/geonode pull request #12212
Opened 2024-05-08 14:56 UTC by giohappy

2024-05-09 09:56 UTC, etj commented on geonode/__init__.py
> +__version__ = (4, 2, 4, "dev", 0)
4.2.5 dev

2024-05-09 09:57 UTC, etj requested changes
dev version is wrong

2024-05-09 11:26 UTC, giohappy commented
> dev version is wrong

@etj what do you mean?
BTW I've bumped to 4.2.5

2024-05-09 11:32 UTC, etj commented on setup.cfg
> +    django-geonode-mapstore-client>=4.1.1,<5.0.0
are we sure about `>=4.1.1`, shouldnt it be `>=4.2.0` ?

2024-05-10 08:41 UTC, etj approved these changes

2024-05-10 08:45 UTC, mattiagiupponi approved these changes

2024-05-10 08:50 UTC, merged