GNIP 97: New metadata editor
GeoNode/geonode pull request #12794
Opened 2024-12-19 16:39 UTC by etj

Complete rewriting of the metadata editor according to [GNIP 97](https://github.com/GeoNode/geonode/issues/11511)

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] PR title must be in the form "[Fixes #<issue_number>] Title of the PR"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: black geonode && flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

2024-12-20 08:55 UTC, gannebamm commented
Can you please add some very short instructions on how to test it? Either here or (better?) at the GNIP?

2024-12-20 09:04 UTC, giohappy commented
@gannebamm today the GNIP will be updated. There's so much to write! We hope it will be ready by the end of the day, otherwise we will complete it in January, after holidays.

2024-12-20 13:14 UTC, etj commented
@gannebamm I added some info on the internals at https://github.com/GeoNode/geonode/issues/11511

Since we didn't merge the client part yet, you should install it by hand
```bash
pip install git+https://github.com/GeoNode/geonode-mapstore-client.git@metadata_manager_build#egg=django_geonode_mapstore_client
```
We didnt want to set this branch in the requirementsin the PR.

2025-01-07 11:36 UTC, etj commented
Hi @gannebamm, happy new year!  
Did you manage to test the new editor?

2025-01-10 17:23 UTC, mattiagiupponi requested changes

2025-01-10 17:23 UTC, mattiagiupponi commented on geonode/base/api/views.py
> -        ).data
is there any reason why the serializer is no longer used?

2025-01-10 17:23 UTC, mattiagiupponi commented on geonode/inspire/metadata.py
> +class INSPIREHandler(MetadataHandler):
From my undestanding, the inspire app is not totally required, is more a documentation app. If is not used, i would propose to switch it as documentation or if is needed for testing purpose only, i would document this and move the app in the tests.
Is open to discussion

2025-01-10 17:23 UTC, mattiagiupponi commented on geonode/metadata/api/views.py
> +                        "POST": ["change_resourcebase_metadata"],
Should this be PUT si is the method used in the function?

2025-01-13 11:11 UTC, etj commented
Hi @ridoo 

#####  `geonode:handler`

> The handler will know the schema parts it is responsible for, won't it?

The `MetadataManager` class is responsible for dispatching the field handling to the proper handler: the `geonode:handler` info tells which handler is to be called.
The handling override mechanism foresees that an handler may declare itself as the main handler for an existing field, so different handlers may work on the same field, but only the last declared one will be invoked, that is the one that lastly set himself as `geonode:handler`.

See this for example:
https://github.com/GeoNode/geonode/blob/7e81443a2a3db3c3e92bb30882c75ccbd69fc732/geonode/inspire/metadata.py#L52-L58

#####  `geonode:required`

> so for which cases geonode:required is necessary? 

JSON schema defines the required fields (using the annotation `required`) in a level above the sub schema definition.
The handlers only work on their own sub schema.
The `MetadataManager` uses the `geonode:required` custom annotations to build the upper level `required` array: https://github.com/GeoNode/geonode/blob/7e81443a2a3db3c3e92bb30882c75ccbd69fc732/geonode/metadata/manager.py#L78-L85

2025-01-13 11:15 UTC, etj commented on geonode/base/api/views.py
> -        ).data
It **is** used indeed.
Please note that the code you're pointing to has changed name from `base_linked_resources_payload` to  `base_linked_resources_instances`.  The new `base_linked_resources_payload` calls `base_linked_resources_instances` (now also used elsewere for DRY), and still uses the serializer, returning the same content as before.

2025-01-13 11:18 UTC, etj commented on geonode/inspire/metadata.py
> +class INSPIREHandler(MetadataHandler):
Pls note that I used the inspire app for an example in this very thread (https://github.com/GeoNode/geonode/pull/12794#issuecomment-2586817938). It is a really good point for documentation and testing handler overriding. I know it is something not used outside Europe, but I guess we need some real override implementation inside geonode.

2025-01-15 09:50 UTC, mattiagiupponi requested changes

2025-01-15 09:50 UTC, mattiagiupponi commented on geonode/metadata/api/views.py
> +    lang = remove_country_from_languagecode(get_language())
Side note: i see that here we use `get_language()` while or the schema we use `get_language_from_request(request) ` is not better to use the same function enverywhere?

2025-01-15 09:50 UTC, mattiagiupponi commented on geonode/metadata/api/views.py
> +            qs = get_user_model().objects.all()
I dont think makes much sense. Inside the `get_available_users` we filter the user based on what the user can see, but if we dont give a user, will return all. I guess here is better to return 0 users if the user is not provided. (even because even the Anonymous user will match the first `if` so this else will never be met)

2025-01-15 09:50 UTC, mattiagiupponi commented on geonode/metadata/handlers/abstract.py
> +class MetadataFieldException(Exception):
I guess to make it more linear, will be better to move this 3 exception is another file `exceptions.py`

2025-01-15 09:50 UTC, mattiagiupponi commented on geonode/upload/migrations/0050_alter_uploadsizelimit_max_size.py
> +from django.db import migrations, models
I guess this migration is not needed. The maxsize is an environment variable that can change based on the user that creates the migrations. I think that it should be removed and we should keep a static value anyway is updatable via admin interface

2025-01-15 09:55 UTC, etj commented on geonode/metadata/api/views.py
> +        methods=["get", "put", "patch"],
it was used by the client in the first implementations, to be removed indeed

2025-01-15 09:57 UTC, etj commented on geonode/metadata/api/views.py
> +    lang = remove_country_from_languagecode(get_language())
`get_language_from_request` does not work with `WSGIRequest`, so in that case `get_language` is the only way. I would still use `get_language_from_request` whenever possibile, bc it's the right way the language should be handled

2025-01-15 10:08 UTC, etj commented on geonode/upload/migrations/0050_alter_uploadsizelimit_max_size.py
> +from django.db import migrations, models
@Gpetrak you added this along with the tests. Is it needed?
https://github.com/GeoNode/geonode/blob/metadata_manager/geonode/upload/migrations/0050_alter_uploadsizelimit_max_size.py

2025-01-15 15:35 UTC, mattiagiupponi approved these changes

2025-01-15 16:26 UTC, merged