removes use of six library
GeoNode/geonode pull request #6839
Opened 2021-01-19 03:42 UTC by burner761

<Include a few sentences describing the overall goals for this Pull Request>

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

2021-01-19 10:22 UTC, afabiani approved these changes

2021-01-19 11:18 UTC, afabiani commented
@burner761 can you please take a look at the new LGTM issues introduced with this PR?

2021-01-20 03:46 UTC, mtnorthcott requested changes
`six` can still be removed from the following:
* geonode/social/tests.py
* geonode/geoapps/api/serializers.py
* geonode/geoserver/tasks.py
* requirements.txt

2021-01-20 03:46 UTC, mtnorthcott commented on geonode/monitoring/collector.py
> +                                  'value_num': value if isinstance(value, int + (float, Decimal,)) else None})
`integer_types` is a collection/sequence so `integer_types + (float, Decimal)` extends the sequence. `int` is not a sequence and does not support the `+` operation on the `tuple` type. Please fix this to simply contain `int` within the `tuple`.

2021-01-28 16:56 UTC, afabiani requested changes
There are some conflicts, moreover see if it is possible to solve the new LGTM issues.

2021-02-10 08:52 UTC, afabiani approved these changes

2021-02-10 08:52 UTC, merged