made it so all the files that are opened get closed
GeoNode/geonode pull request #6840
Opened 2021-01-19 03:45 UTC by burner761

I have made sure that when a file is opened using
file = open() 
it is closed later in the file and when is possible converted it to from
with open() as file:

2021-01-19 10:22 UTC, afabiani approved these changes

2021-01-19 10:23 UTC, afabiani commented
@burner761 can you please remove the "worker.state" bin file from this PR?

2021-01-19 10:25 UTC, afabiani requested changes
Please remove `worker.state` bin from the PR

2021-01-20 01:21 UTC, mtnorthcott requested changes
Minor changes here. Also please check your indentation.

2021-01-20 01:21 UTC, mtnorthcott commented on geonode/tests/utils.py
> +                ext, _ = spatial_file.split('_')
Seems unnecessary to compute the filename if `params[spatial_file]` and `params['tif_file']` can be checked to see if they are open file descriptors. Something along the lines of
```python
for spatial_file in spatial_files:
    if isinstance(params[spatial_file], file):
        params[spatial_files].close()

if isinstance(params['tif_file'], file):
    params['tif_file'].close()

2021-01-21 22:34 UTC, mtnorthcott requested changes

2021-01-21 22:34 UTC, mtnorthcott commented on geonode/geoserver/helpers.py
> +
Please remove these extra lines

2021-01-28 16:24 UTC, merged