[Issue #6843] Fetch dictionary keys with dict.get(...) where appropriate to provide default value
GeoNode/geonode pull request #6845
Opened 2021-01-20 01:12 UTC by rukarangi

Replaced dict key look ups with .get() to provide default values where applicable. i.e Replacing inline conditionals when looking up key in dictionary.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [x] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

2021-01-20 01:29 UTC, mtnorthcott requested changes
Minor fixes needed.

2021-01-20 01:29 UTC, mtnorthcott commented on geonode/layers/utils.py
> +                            _pwd = _ogc_server_settings('PASSWORD', 'geoserver')
You're missing the `.get(...)` call here.

2021-01-20 01:29 UTC, mtnorthcott commented on geonode/maps/tests.py
> +        abstract = config_map('abstract', config_map['about']['abstract'])
And here.

2021-01-21 22:41 UTC, mtnorthcott approved these changes

2021-01-28 16:57 UTC, afabiani approved these changes

2021-01-28 16:57 UTC, merged