[Issue #6843] Replace concatenated strings, %-strings, and str.format with f-strings
GeoNode/geonode pull request #6852
Opened 2021-01-20 23:25 UTC by sarahsmi

Replace concatenated strings, %-strings, and str.format with f-strings

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

2021-01-21 22:17 UTC, mtnorthcott requested changes
I probably haven't caught all occurrences but please check places where you have tried accessing dictionary keys within your curly braces. In some cases, the string is closed early which will result in a syntax error.

2021-01-21 22:17 UTC, mtnorthcott commented on geonode/settings.py
> +    'spatialite:///{os.path.join(PROJECT_ROOT, 'development.db'}')
Single quote problem

2021-01-21 22:17 UTC, mtnorthcott commented on geonode/settings.py
> +LOGOUT_URL = os.getenv(f'LOGOUT_URL', '{SITEURL}account/logout/')
`f` character is preceding the incorrect string

2021-01-21 22:17 UTC, mtnorthcott commented on geonode/tests/smoke.py
> +            f"{settings.SITEURL[:-1]}{reverse("account_login")}?next=http%3A//testserver{target_url}"
Double quote problem

2021-01-21 22:17 UTC, mtnorthcott commented on geonode/tests/smoke.py
> +            f"{settings.SITEURL[:-1]}{reverse("account_login")}?next=http%3A//testserver{target_url}"
Double quote problem

2021-01-21 22:17 UTC, mtnorthcott commented on geonode/tests/smoke.py
> +            f"{settings.SITEURL[:-1]}{reverse("account_login")}?next=http%3A//testserver{target_url}"
Double quote problem

2021-01-21 22:17 UTC, mtnorthcott commented on geonode/upload/views.py
> +        logger.debug(f"valid_extensions: {form.cleaned_data["valid_extensions"]}")
Double quote problem

2021-01-21 22:17 UTC, mtnorthcott commented on geonode/urls.py
> +    notifications_urls = fS'{settings.NOTIFICATIONS_MODULE}.urls'
Typo

2021-01-21 22:17 UTC, mtnorthcott commented on geonode/utils.py
> +    social_url = f"{("https" if request.is_secure() else "http")}://{request.get_host()}{request.get_full_path()}"
Double quote problem

2021-01-21 22:17 UTC, mtnorthcott commented on geonode/utils.py
> +                        new_field_name = new_field_name[:-2] + f'_{j}'
Can also remove the concatenation with `f'{new_field_name[:-2]}_{j}'`

2021-01-21 22:17 UTC, mtnorthcott commented on tasks.py
> +                "url": f"{os.environ['GEOSERVER_PUBLIC_LOCATION']S}",
Typo

2021-03-17 11:45 UTC, afabiani commented
Superseded by https://github.com/GeoNode/geonode/pull/7096

Please use that branch if you need to continue working on that one.

2021-03-17 11:45 UTC, closed without merging