[#6799] removed use of some magic numbers
GeoNode/geonode pull request #6853
Opened 2021-01-21 03:01 UTC by burner761

this Request seeks to make the code more readable by reducing the use of magic numbers which can confuse people who want to edit the code in the future.

2021-01-21 03:55 UTC, mtnorthcott requested changes
Mainly style changes.

2021-01-21 03:55 UTC, mtnorthcott commented on geonode/static/geonode/js/cookie-law-info/cookie-law-info-public.js
> +
Revert indentation here.

2021-01-21 03:55 UTC, mtnorthcott commented on geonode/static/geonode/js/ol-2.13/lib/deprecated.js
> +XMLisLoaded = 4;
Inconsistent use of semicolons here. Also could probably declare these as `const`

2021-01-21 03:55 UTC, mtnorthcott commented on geonode/static/geonode/js/ol-2.13/lib/deprecated.js
> +        var fullRot = 360;
Define as a `const`

2021-01-21 03:55 UTC, mtnorthcott commented on geonode/static/geonode/js/ol-2.13/lib/deprecated.js
> +        mouseSensitivity = 5
Define as a `const`

2021-01-21 03:55 UTC, mtnorthcott commented on geonode/static/geonode/js/ol-2.13/lib/deprecated.js
> +        var scrollSensitivity = 120;
Define as a `const`

2021-01-21 03:55 UTC, mtnorthcott commented on geonode/utils.py
> +maxExtent = 20037508.34;
Global constants in Python should be capitalised.

2021-01-21 03:55 UTC, mtnorthcott commented on geonode/utils.py
> +fullRot = 360;
Global constants in Python should be capitalised.

2021-01-26 12:58 UTC, t-book commented
@mtnorthcott This looks good for me, ready for merge from your side?

2021-01-26 21:09 UTC, mtnorthcott approved these changes

2021-01-26 21:10 UTC, mtnorthcott commented
@t-book Looks good to me

2021-01-26 21:15 UTC, t-book commented
nice thanks @mtnorthcott 

- Code looks good to me
- Tested live, no regression spotted.

Merged.

2021-01-26 21:15 UTC, merged