[Fixes #7068] mixed case TopicCategories are mangled during layer upload
GeoNode/geonode pull request #7069
Opened 2021-03-11 14:25 UTC by stefmec

Categories are stored in mixed case in the database but where converted to lowercase during upload. This fix keeps the case.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

2021-03-18 08:43 UTC, gannebamm commented on geonode/layers/tests.py
> +        'planningCadastre', # mixed case default category
@stefmec please fix the PEP8 formatting errors:

^@^@geonode/layers/tests.py:1354:28: E261 at least two spaces before inline comment
geonode/layers/tests.py:1368:21: E128 continuation line under-indented for visual indent
geonode/layers/tests.py:1370:21: E128 continuation line under-indented for visual indent
geonode/layers/tests.py:1404:5: E303 too many blank lines (2

2021-03-18 09:57 UTC, afabiani requested changes

2021-03-18 09:57 UTC, afabiani commented on geonode/layers/tests.py
> +            print(_l.name)
Do not use print statements please. Use logger instead

2021-03-18 11:54 UTC, afabiani approved these changes

2021-03-18 20:18 UTC, gannebamm commented
The uuid test fails with an http error? I do not think that error is related to the changes in this PR. Has circleCI timeout issues?

2021-03-18 20:25 UTC, t-book commented
@gannebamm This is not connected. Unfortunately, the Upload-Test is failing regularly. @afabiani and I already tried some things to solve it. No luck so far. Maybe https://circleci.com/docs/2.0/ssh-access-jobs/ could shed light into ...

2021-03-18 20:36 UTC, merged

2021-03-19 07:23 UTC, gannebamm commented
The backports failed? @afabiani do you know why? Shouldn't be 3.2.x specific Code in this PR.

2021-03-19 08:43 UTC, afabiani commented
@gannebamm backporter on both 3.2.x and 3.1.x