Re-implement thesaurus import/export using rdflib to support a wider range of RDF formats [Fixes #8701]
GeoNode/geonode pull request #8702
Opened 2022-01-27 16:42 UTC by mikesname

This patch revises the `load_thesaurus` and `dump_thesaurus` management commands to use [`rdflib`](https://rdflib.readthedocs.io/en/stable/), rather than bespoke XML parsing. This allows importing and exporting a range of RDF formats rather than just one flavour of RDF/XML.

Aside from these commands and the addition of `rdflib` to the `requirements.txt`, the only other change is increasing the length of the `ThesaurusKeywordLabel.lang` field from 3 to 255, since there's not really a limit on RDF language tag length.

I have added additional tests for the `dump_thesaurus` command.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [x] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [x] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [x] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

2022-01-27 16:50 UTC, mikesname commented on requirements.txt
> +rdflib==6.1.1
Done!

2022-01-27 17:09 UTC, mikesname commented
Sorry, I forced pushed a couple of changes here when I had to redo the migration with updates from master. Shalln't do that again. If need be I'll convert the PR to a draft till I've worked through the inevitable issues...

2022-01-31 09:20 UTC, mattiagiupponi requested changes
Hi, @mikesname thanks for the contribution.
Overall looks good, just a few points:
- Can u also update the [official documentation](https://github.com/GeoNode/documentation) for the `dump_thesaurus` command? So we can keep it updated with the new parameters that are added to the command
- I have some doubts related to the output format of the dump.
I usually use the "GEMET - INSPIRE themes, version 1.0" thesaurus for my test, and the beginning of the file looks wrong. 
Original file
```xml
<skos:ConceptScheme xmlns:skos="http://www.w3.org/2004/02/skos/core#" rdf:about="http://inspire.ec.europa.eu/theme">
  <dc:title xmlns:dc="http://purl.org/dc/elements/1.1/">GEMET - INSPIRE themes, version 1.0</dc:title>
  <dcterms:issued xmlns:dcterms="http://purl.org/dc/terms/">2018-05-23T10:25:56</dcterms:issued>
  <dcterms:modified xmlns:dcterms="http://purl.org/dc/terms/">2018-05-23T10:25:56</dcterms:modified>
</skos:ConceptScheme>
<skos:Concept xmlns:skos="http://www.w3.org/2004/02/skos/core#" rdf:about="http://inspire.ec.europa.eu/theme/of">
  <skos:prefLabel xml:lang="en">Oceanographic geographical features</skos:prefLabel>
  <skos:scopeNote xml:lang="en">Physical conditions of oceans (currents, salinity, wave heights, etc.).</skos:scopeNote>
  <skos:altLabel>of</skos:altLabel>
  <skos:inScheme rdf:resource="http://inspire.ec.europa.eu/theme" />
</skos:Concept>
```

Dump:
```xml
<skos:Concept rdf:about="http://inspire.ec.europa.eu/theme/of">
    <skos:inScheme>
      <skos:ConceptScheme rdf:about="http://inspire.ec.europa.eu/theme">
        <dc:title>GEMET - INSPIRE themes, version 1.0</dc:title>
        <dc:description>GEMET - INSPIRE themes, version 1.0</dc:description>
        <dcterms:issued>2018-05-23T10:25:56</dcterms:issued>
      </skos:ConceptScheme>
    </skos:inScheme>
    <skos:altLabel>of</skos:altLabel>
    <skos:prefLabel xml:lang="en">Oceanographic geographical features</skos:prefLabel>
  </skos:Concept>
```
It looks like the header of the thesaurus has been mixed with one of the labels.

Following the file used:
- inspire-theme (the original thesaurus)
- test2 the output from the dump
[thesaurus.zip](https://github.com/GeoNode/geonode/files/7969552/thesaurus.zip)

(had to zip them since GitHub doesn't support RDF

2022-01-31 16:48 UTC, mikesname commented
Hi @mattiagiupponi, okay I've attempted to put in a [PR for that](https://github.com/GeoNode/documentation/pull/217).

2022-02-02 08:44 UTC, merged