[Backport 3.3.x] [Fixes #9013] Advanced Workflow: workflow logic should take precedence over standard permissions
GeoNode/geonode pull request #9023
Opened 2022-04-03 13:37 UTC by afabiani

References: #9013

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [ ] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [ ] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [ ] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [ ] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

2022-04-04 14:08 UTC, marthamareal commented
@afabiani , On testing

For `ADVANCED WORKFLOW`
    - If the `owner group` is different from the `resource group`, The group manager of the resource group is unable to access the resource.
    - 
For `SIMPLIFIED WORKFLOW`
    - Resource is created when both `is_published and is_approved` = False
    - Approving the resource has no effect on owner perms and also Anonymous can not access it.

For `SIMPLE PUBLISHING`
    - Resource is created when both `is_published and is_approved` = False

2022-04-04 14:32 UTC, marthamareal commented
@afabiani

1. For `SIMPLIFIED WORKFLOW` Anonymous can not see a resource after updating the fields `is_published and is_approved` to `True`.

2. An example for `ADVANCED WORKFLOW` issue:
- create a resource as owner in group 1
- Login as an admin and assign the above resource to group 2
- Notice Managers of group2 can not access the above resource

2022-04-04 16:20 UTC, mattiagiupponi requested changes
@afabiani which are the part related to the advanced workflow? there are a lot of different development here (OGC_Servers_Handler, test changed, new tests) which looks like that are out of the issue scope

2022-04-04 17:13 UTC, afabiani commented
@marthamareal please check again, the issues you pointed out should be new fixed.

2022-04-05 16:37 UTC, mattiagiupponi commented on geonode/base/models.py
> +                _group_status_changed = self.group != ResourceBase.objects.get(pk=self.get_self_resource().pk).group
If you already have the resource, is not enough to do:
```python
_group_status_changed = self.group != self.get_self_resource().group
```

2022-04-06 07:39 UTC, merged