remove quotes from GEOSERVER_JAVA_OPTS in .env files
GeoNode/geonode pull request #9920
Opened 2022-08-27 15:43 UTC by categulario

Attempt to solve #9519 as per the discovery mentioned in comment https://github.com/GeoNode/geonode/issues/9519#issuecomment-1229210485 by removing quotes from `GEOSERVER_JAVA_OPTS` variable in the various `.env*` files.

According to the [docker docs](https://docs.docker.com/compose/env-file/#syntax-rules) the quotes are understood as part of the value.

Reading a little bit more of the source and commit history I see that quotes where introduced in 1fdfb47fb7737c761357fdc06e79f92b9c71d913 and then added to some other variables. Now I'm wondering how this worked at all. And that leaves the following question: what happens to the other values that are also quoted? Should they be unquoted?

## Questions

* Is there a way to add tests for this?
* Do I need to sign the contributor agreement for this?
* Who made the process of contributing so bureaucratic and complicated?

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

For all pull requests:

- [x] Confirm you have read the [contribution guidelines](https://github.com/GeoNode/geonode/blob/master/CONTRIBUTING.md) 
- [ ] You have sent a Contribution Licence Agreement (CLA) as necessary (not required for small changes, e.g., fixing typos in the documentation)
- [x] Make sure the first PR targets the master branch, eventual backports will be managed later. This can be ignored if the PR is fixing an issue that only happens in a specific branch, but not in newer ones.

The following are required only for core and extension modules (they are welcomed, but not required, for contrib modules):
- [x] There is a ticket in https://github.com/GeoNode/geonode/issues describing the issue/improvement/feature (a notable exemption is, changes not visible to end-users)
- [ ] The issue connected to the PR must have Labels and Milestone assigned
- [x] PR for bug fixes and small new features are presented as a single commit
- [ ] Commit message must be in the form "[Fixes #<issue_number>] Title of the Issue"
- [ ] New unit tests have been added covering the changes, unless there is an explanation on why the tests are not necessary/implemented
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] This PR passes the QA checks: flake8 geonode
- [ ] Commits changing the **settings**, **UI**, **existing user workflows**, or adding **new functionality**, need to include documentation updates
- [ ] Commits adding **new texts** do use gettext and have updated .po / .mo files (without location infos)

**Submitting the PR does not require you to check all items, but by the time it gets merged, they should be either satisfied or inapplicable.**

2022-08-29 08:13 UTC, afabiani approved these changes

2022-08-29 08:35 UTC, afabiani requested changes
I guess this has something to do with your docker environment.
We use the quotes since long time and actually I can't see any issue.
On the other hand, by removing them we cannot build the container at all

```
NOTICE:  extension "postgis" already exists, skipping
CREATE EXTENSION
NOTICE:  extension "postgis" already exists, skipping
CREATE EXTENSION
./.env_test: line 111: -Xms2G: command not found

Exited with code exit status 127
CircleCI received exit code 127
```

2022-08-30 12:54 UTC, categulario commented
what command did you run to get that error? perhaps, like you said it is a difference in the environment. However I was following the guide, so maybe something is not properly specified there?

2022-08-30 15:17 UTC, afabiani commented
I used the default `.env` provided with GeoNode which has the quotes, and run:

`docker-compose build`

By removing the quotes I get the error above. CircleCI also behaves the same.

Could it be an issue with the `docker` and `docker-compose` versions?

2022-09-07 14:13 UTC, closed without merging